import React, { useEffect } from 'react';
import { useForm } from 'react-hook-form';
import {
  Box,
  Button,
  Card,
  CardContent,
  Typography,
  Paper,
  Grid,
  TextField,
  FormControlLabel,
  Checkbox
} from '@mui/material';
import { FinancialCommitment, CommitmentType, CompletionStatus } from '../types';
// Import our new modular components and configuration
import { getFieldConfig, shouldShowField, FieldName } from './form-fields/CommitmentFieldConfig';
import {
  TypeSelector,
  BalanceField,
  MonthlyPaymentField,
  CompletionStatusSelector,
  RepaymentAmountField,
  NotesField,
  IncludeInMortgageField,
  RetirementAgeField
} from './form-fields/CommitmentFormFields';

interface CommitmentFormProps {
  onAddCommitment: (commitment: Omit<FinancialCommitment, 'id'>) => void;
  existingCommitment?: FinancialCommitment;
  onUpdateCommitment?: (commitment: FinancialCommitment) => void;
  onCancel?: () => void;
}

const CommitmentForm: React.FC<CommitmentFormProps> = ({
  onAddCommitment,
  existingCommitment,
  onUpdateCommitment,
  onCancel,
}) => {
  const isEditing = !!existingCommitment;
  
  // Define the form values type based on whether we're editing or creating
  type FormValues = Omit<FinancialCommitment, 'id'> & { id?: string };
  
  const { register, handleSubmit, watch, formState: { errors }, setValue, reset } = useForm<any>({
    defaultValues: existingCommitment || {
      type: '',
      balance: 0,
      monthlyPayment: undefined,
      completionStatus: 'nothing',
      repaymentAmount: undefined,
      includeInMortgage: false,
      notes: '',
      retirementAge: 65,
    },
  });

  // Reset form when existingCommitment changes
  useEffect(() => {
    if (existingCommitment) {
      reset(existingCommitment);
    }
  }, [existingCommitment, reset]);

  // Watch for changes in type and completion status to dynamically update the form
  const selectedType = watch('type') as CommitmentType;
  const completionStatus = watch('completionStatus') as CompletionStatus;
  const monthlyPayment = watch('monthlyPayment');
  const balance = watch('balance');
  const hasBulletPayment = watch('hasBulletPayment');
  const formValuesForConditionals = React.useMemo(() => ({
    type: selectedType,
    completionStatus,
    monthlyPayment,
    balance,
    hasBulletPayment,
  }), [selectedType, completionStatus, monthlyPayment, balance, hasBulletPayment]);
  
  // Get the field configuration based on the selected type and completion status
  const fieldConfig = React.useMemo(() => {
    return getFieldConfig(selectedType, completionStatus, formValuesForConditionals);
  }, [selectedType, completionStatus, formValuesForConditionals]);
  
  // Reset fields that are no longer applicable when type or completion status changes
  useEffect(() => {
    // Define all field names to check
    const fieldNames: FieldName[] = [
      'balance',
      'monthlyPayment',
      'repaymentAmount',
      'notes',
      'includeInMortgage',
      'retirementAge',
      'termRemainingMonths',
      'termRemainingYears',
      'willMortgageRepayThis'
    ];
    
    // For each field, check if it should be shown
    fieldNames.forEach(fieldName => {
      // If field should not be shown, reset its value
      if (!shouldShowField(fieldName, fieldConfig, formValuesForConditionals)) {
        if (fieldName === 'balance') {
          setValue('balance', 0);
        } else if (fieldName === 'includeInMortgage') {
          setValue('includeInMortgage', false);
        } else if (fieldName === 'retirementAge') {
          setValue('retirementAge', 65);
        } else if (fieldName === 'notes') {
          setValue('notes', '');
        } else {
          setValue(fieldName, undefined);
        }
      }
    });
  }, [selectedType, completionStatus, fieldConfig, setValue, formValuesForConditionals]);

  const onSubmit = (data: any) => {
    if (isEditing && onUpdateCommitment) {
      onUpdateCommitment(data as FinancialCommitment);
    } else {
      // When adding, we don't need the id as it will be generated by the slice
      const { id, ...commitmentWithoutId } = data;
      onAddCommitment(commitmentWithoutId);
    }
  };

  return (
    <Paper elevation={2} sx={{ p: 3, mb: 3 }}>
      <form onSubmit={handleSubmit(onSubmit)}>
        <Typography variant="h6" gutterBottom>
          {isEditing ? 'Edit Financial Commitment' : 'Add Financial Commitment'}
        </Typography>

        <Grid container spacing={3}>
          {/* Type selector - always shown */}
          <TypeSelector register={register} watch={watch} errors={errors} setValue={setValue} fieldConfig={fieldConfig} />

          {/* Balance field - conditionally shown */}
          {shouldShowField('balance', fieldConfig, formValuesForConditionals) && (
            <BalanceField register={register} errors={errors} fieldConfig={fieldConfig} />
          )}

          {/* Monthly payment field - conditionally shown */}
          {shouldShowField('monthlyPayment', fieldConfig, formValuesForConditionals) && (
            <MonthlyPaymentField register={register} errors={errors} fieldConfig={fieldConfig} />
          )}

          {/* Completion status selector - always shown */}
          <CompletionStatusSelector register={register} watch={watch} errors={errors} fieldConfig={fieldConfig} setValue={setValue} />

          {/* Repayment amount field - conditionally shown */}
          {shouldShowField('repaymentAmount', fieldConfig, formValuesForConditionals) && (
            <RepaymentAmountField register={register} errors={errors} fieldConfig={fieldConfig} />
          )}

          {/* Notes field - conditionally shown */}
          {shouldShowField('notes', fieldConfig, formValuesForConditionals) && (
            <NotesField register={register} errors={errors} fieldConfig={fieldConfig} />
          )}

          {/* Include in mortgage field - conditionally shown */}
          {shouldShowField('includeInMortgage', fieldConfig, formValuesForConditionals) && (
            <IncludeInMortgageField register={register} watch={watch} errors={errors} fieldConfig={fieldConfig} />
          )}
          
          {/* Term remaining fields - conditionally shown */}
          {shouldShowField('termRemainingMonths', fieldConfig, formValuesForConditionals) && (
            <Grid item xs={12} md={6}>
              <TextField
                {...register("termRemainingMonths")}
                label={fieldConfig.labels.termRemainingMonths}
                type="number"
                fullWidth
                error={!!errors.termRemainingMonths}
                helperText={errors.termRemainingMonths?.message?.toString()}
              />
            </Grid>
          )}

          {shouldShowField('termRemainingYears', fieldConfig, formValuesForConditionals) && (
            <Grid item xs={12} md={6}>
              <TextField
                {...register("termRemainingYears")}
                label={fieldConfig.labels.termRemainingYears}
                type="number"
                fullWidth
                error={!!errors.termRemainingYears}
                helperText={errors.termRemainingYears?.message?.toString()}
              />
            </Grid>
          )}

          {/* Has Bullet Payment field - conditionally shown for hire_purchase */}
          {shouldShowField('hasBulletPayment', fieldConfig, formValuesForConditionals) && (
            <Grid item xs={12}>
              <FormControlLabel
                control={
                  <Checkbox
                    {...register("hasBulletPayment")}
                    checked={!!watch("hasBulletPayment")}
                  />
                }
                label={fieldConfig.labels.hasBulletPayment}
              />
            </Grid>
          )}

          {/* Bullet Payment Amount field - conditionally shown based on hasBulletPayment */}
          {shouldShowField('bulletPaymentAmount', fieldConfig, formValuesForConditionals) && (
            <Grid item xs={12} md={6}>
              <TextField
                {...register("bulletPaymentAmount")}
                label={fieldConfig.labels.bulletPaymentAmount}
                type="number"
                fullWidth
                error={!!errors.bulletPaymentAmount}
                helperText={errors.bulletPaymentAmount?.message?.toString()}
              />
            </Grid>
          )}

          {/* Will mortgage repay this - conditionally shown */}
          {shouldShowField('willMortgageRepayThis', fieldConfig, formValuesForConditionals) && (
            <Grid item xs={12}>
              <FormControlLabel
                control={
                  <Checkbox
                    {...register("willMortgageRepayThis")}
                    checked={!!watch("willMortgageRepayThis")}
                    onChange={(e) => {
                      setValue("willMortgageRepayThis", e.target.checked);
                    }}
                  />
                }
                label={fieldConfig.labels.willMortgageRepayThis}
              />
            </Grid>
          )}
          
          {/* Retirement age field - conditionally shown */}
          {shouldShowField('retirementAge', fieldConfig, formValuesForConditionals) && (
            <RetirementAgeField register={register} watch={watch} errors={errors} />
          )}
        </Grid>

        <Box sx={{ display: 'flex', justifyContent: 'flex-end', mt: 3 }}>
          {onCancel && (
            <Button onClick={onCancel} sx={{ mr: 1 }}>
              Cancel
            </Button>
          )}
          <Button type="submit" variant="contained" color="primary">
            {isEditing ? 'Update' : 'Add'}
          </Button>
        </Box>
      </form>
    </Paper>
  );
};

export default CommitmentForm;
