import React, { useEffect } from 'react';
import { useForm } from 'react-hook-form';
import {
  Box,
  Button,
  Typography,
  Paper,
  Grid,
} from '@mui/material';
import { FinancialCommitment, CommitmentType, CompletionStatus } from '../types';
// Import our new modular components and configuration
import { getFieldConfig, shouldShowField } from './form-fields/CommitmentFieldConfig';
import {
  TypeSelector,
  BalanceField,
  MonthlyPaymentField,
  CompletionStatusSelector,
  RepaymentAmountField,
  NotesField,
  IncludeInMortgageField,
  RetirementAgeField
} from './form-fields/CommitmentFormFields';

interface CommitmentFormProps {
  onAddCommitment: (commitment: Omit<FinancialCommitment, 'id'>) => void;
  existingCommitment?: FinancialCommitment;
  onUpdateCommitment?: (commitment: FinancialCommitment) => void;
  onCancel?: () => void;
}

const CommitmentForm: React.FC<CommitmentFormProps> = ({
  onAddCommitment,
  existingCommitment,
  onUpdateCommitment,
  onCancel,
}) => {
  const isEditing = !!existingCommitment;
  
  // Define the form values type based on whether we're editing or creating
  type FormValues = Omit<FinancialCommitment, 'id'> & { id?: string };
  
  const { control, handleSubmit, watch, formState: { errors }, setValue } = useForm<any>({
    defaultValues: existingCommitment || {
      type: 'credit_card',
      balance: 0,
      monthlyPayment: undefined,
      completionStatus: 'nothing',
      repaymentAmount: undefined,
      includeInMortgage: false,
      notes: '',
      retirementAge: 65, // Default retirement age
    },
  });

  // Watch for changes in type and completion status to dynamically update the form
  const selectedType = watch('type') as CommitmentType;
  const completionStatus = watch('completionStatus') as CompletionStatus;
  
  // Get the field configuration based on the selected type and completion status
  const fieldConfig = getFieldConfig(selectedType, completionStatus);
  
  // Reset fields that are no longer applicable when type or completion status changes
  useEffect(() => {
    // If balance field is hidden, reset its value
    if (!fieldConfig.showBalance) {
      setValue('balance', 0);
    }
    
    // If monthly payment field is hidden, reset its value
    if (!fieldConfig.showMonthlyPayment) {
      setValue('monthlyPayment', undefined);
    }
    
    // If repayment amount field is hidden, reset its value
    if (!fieldConfig.showRepaymentAmount) {
      setValue('repaymentAmount', undefined);
    }
  }, [selectedType, completionStatus, fieldConfig, setValue]);

  const onSubmit = (data: any) => {
    if (isEditing && onUpdateCommitment) {
      onUpdateCommitment(data as FinancialCommitment);
    } else {
      // When adding, we don't need the id as it will be generated by the slice
      const { id, ...commitmentWithoutId } = data;
      onAddCommitment(commitmentWithoutId);
    }
  };

  return (
    <Paper elevation={2} sx={{ p: 3, mb: 3 }}>
      <form onSubmit={handleSubmit(onSubmit)}>
        <Typography variant="h6" gutterBottom>
          {isEditing ? 'Edit Financial Commitment' : 'Add Financial Commitment'}
        </Typography>

        <Grid container spacing={3}>
          {/* Type selector - always shown */}
          <TypeSelector control={control} errors={errors} fieldConfig={fieldConfig} />

          {/* Balance field - conditionally shown */}
          {shouldShowField('showBalance', fieldConfig) && (
            <BalanceField control={control} errors={errors} fieldConfig={fieldConfig} />
          )}

          {/* Monthly payment field - conditionally shown */}
          {shouldShowField('showMonthlyPayment', fieldConfig) && (
            <MonthlyPaymentField control={control} errors={errors} fieldConfig={fieldConfig} />
          )}

          {/* Completion status selector - always shown */}
          <CompletionStatusSelector control={control} errors={errors} fieldConfig={fieldConfig} />

          {/* Repayment amount field - conditionally shown */}
          {shouldShowField('showRepaymentAmount', fieldConfig) && (
            <RepaymentAmountField control={control} errors={errors} fieldConfig={fieldConfig} />
          )}

          {/* Notes field - conditionally shown */}
          {shouldShowField('showAdditionalNotes', fieldConfig) && (
            <NotesField control={control} errors={errors} fieldConfig={fieldConfig} />
          )}

          {/* Include in mortgage field - always shown */}
          <IncludeInMortgageField control={control} errors={errors} fieldConfig={fieldConfig} />
          
          {/* Retirement age field - always shown */}
          <RetirementAgeField control={control} errors={errors} />
        </Grid>

        <Box sx={{ display: 'flex', justifyContent: 'flex-end', mt: 3 }}>
          {onCancel && (
            <Button onClick={onCancel} sx={{ mr: 1 }}>
              Cancel
            </Button>
          )}
          <Button type="submit" variant="contained" color="primary">
            {isEditing ? 'Update' : 'Add'}
          </Button>
        </Box>
      </form>
    </Paper>
  );
};

export default CommitmentForm;
